<?php
require_once __DIR__ . '/../includes/auth.php';
requireRole('student');
$user = currentUser();
$pdo = getDB();
$sid = $user['student_id'];

$stmt = $pdo->prepare('SELECT COUNT(*) FROM learning_progress WHERE student_id = ?');
$stmt->execute([$sid]);
$activities = $stmt->fetchColumn();
$stmt = $pdo->prepare('SELECT SUM(time_spent_minutes) FROM learning_progress WHERE student_id = ?');
$stmt->execute([$sid]);
$totalTime = $stmt->fetchColumn() ?: 0;
$stmt = $pdo->prepare('SELECT AVG((g.midterm_grade + g.final_grade)/2) FROM grades g JOIN enrollments e ON g.enrollment_id = e.id WHERE e.student_id = ?');
$stmt->execute([$sid]);
$avgGrade = $stmt->fetchColumn();

$pageTitle = 'Performance & Reports';
require_once __DIR__ . '/../includes/header.php';
?>
<h2 class="mb-4"><i class="bi bi-bar-chart me-2"></i>Student Performance Statistics & History Activity</h2>
<div class="row g-3 mb-4">
    <div class="col-md-4">
        <div class="card stat-card">
            <div class="card-body">
                <h6 class="text-muted">Activities started</h6>
                <h4 class="mb-0"><?= (int)$activities ?></h4>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card stat-card">
            <div class="card-body">
                <h6 class="text-muted">Total time spent (min)</h6>
                <h4 class="mb-0"><?= (int)$totalTime ?></h4>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card stat-card success">
            <div class="card-body">
                <h6 class="text-muted">Average grade</h6>
                <h4 class="mb-0"><?= $avgGrade ? number_format($avgGrade, 1) : '—' ?></h4>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header">School Reports & Analytics / Skill Gaps & Improvement</div>
    <div class="card-body">
        <p class="text-muted mb-0">Detailed reports and skill gap analysis can be generated by your instructor or admin. Your activity history and time spent per activity are tracked in <a href="progress.php">Learning Progress</a>.</p>
    </div>
</div>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
